### PR TITLE
[WIP] New master work tim

### PR DESCRIPTION
**Pull request by TiKeil**
This PR aims to enable plus, minus and product operators for `Functions` as there are only available for `GridFunctions` for now.
Thus, we require combined functions for functions that do not have a grid. I did this by separating the 
combined function completely and we have 

`combined.hh` -> `combined-grid-functions.hh`
 new file  `combined-functions.hh`

Something's wrong with the bindings though. I'm working on it

### CODE REVIEW

**Comment by renefritze** [comment]
Do we want upcasting of a gridless function to a 'gridded' function so we can automagically add those?

Either way, would really like a python test for the stuff too when you're done.

**Comment by renefritze** [comment]
Also, just FYI, I've recently added a convenience method in grid where you don't have know the exact factory name, which can be tedious to construct, like this: https://github.com/dune-community/dune-xt-grid/blob/master/python/dune/xt/grid/__init__.py#L31

Maybe that can help in your failure context here too, if you adapt that for a function factory. If you do, maybe find the right Exception type, my catch is a too general there.

**Comment by TiKeil** [comment]
I found the mistake: https://github.com/dune-community/dune-xt-functions/pull/45/commits/e47c3758b38f422dc7a9063a94f544035458c3b7
It seems everything is in order with the splitting.

**Comment by TiKeil** [comment]
From my point of view, this PR is ready to be merged into #38 . 
@ftalbrecht the bindings splitting is also working well.

**Comment by ftalbrecht** [comment]
Nice work!

**Pull request merged**
