### PR TITLE
[WIP] Introduce bind of functions

### PR DESCRIPTION
**Pull request by TiKeil**

### CODE REVIEW

**Comment by ftalbrecht** [comment]
Since we are currently renaming everything an defining a new API, I would propose to rename `LocalizableFunctionInterface` to `FunctionInterface` (a bit in the spirit of dune-functions vs. dune-localfunctions), as these are _the_ funtions for us. Any objections, @dune-community/dune-xt-devs?

**Comment by renefritze** [comment]
I don't understand the dune-functions vs. dune-localfunctions bit.

**Comment by ftalbrecht** [comment]
Well, there are functions defined on a reference element, and those are in dune-localfunctions. Then there are functions which can be localzed for each grid element, those are in functions.

Similarly, we have functions which can be evaluated in ... Oh by, by writing it it all fell apart.

In general, there are three different kind of functions, of which we currently have two:

1. a (set of) functions which are (i) associated with a reference element or a set of reference elements, and (ii) can be bound to different reference elements (as opposed to grid elements) and (iii) can be evaluated in the coordinates of the reference element.
These could be shape functions of a finite element, before transforming the jacobians. These are in dune-localfunctions, we don't have those.
However, we want to have those for arbitrary codim reference elements, as I argued in #30.
2. a (set of) functions which are (i) associate with grid elements (not reference elements), and (ii) can be bound to different grid elements, and (iii) can be evaluated in the coordinates of the reference element associated with the respective grid element.
We hve those as `LocalFunctionSet` and `LocalFunction`
3. a function which is associated with a grid, which simply (i) knows its name and (ii) yields `LocalFunction` by `localize()` and `localize(element)`.
We have those as `LocalizableFunction`.

In addition we have the `SmoothFunction` which can be evaluated in physical coordinates, but that one does not count.

I think the functions from dune-functions are the ones we call `LocalFunction`, so my original proposal above is probably wrong (I was looking for a better name for `LocalizableFunction`).

So what we need is three good names. What I originally though of was something like (the numbering corresponts to the cases above):

1. `ShapeFunctions`
2. `LocalFunctions`
3. `Functions` (formerly `LocalizableFunction`)

But in accordance with dune-localfunctions and dune-functions (if I understand them correctly), we should probably have

1. `LocalFunctions`
2. `Functions` (formerly `LocalFunctions`)
3. `GridFunction` (formerly `LocalizableFunction`)

If anyone understands dune-localfunctions/dune-functions, please correct me. We should give this some time and think about it. But even if we do not add 1 yet, we could rename the existing ones to be future-proof (TM).

**Comment by TiKeil** [comment]
As far as I understood dune-functions and dune-localfunctions, there does not seem to be a perfectly adjusted naming. According to the description of dune-localfunctions:

> dune-localfunctions: Provides interface and implementation for shape functions defined on the DUNE reference elements. 

In their papers and in the documentary they confusingly call every function in dune-localfunctions a shape (or a local basis) function, but still they do not call it dune-shapefunctions or dune-localbasisfunctions.  From a mathematical point of view, I think we should still distinguish between shape (or local basis) functions and (general) local functions.  

dune-functions however contains `GridFunctions` and `LocalFunctions` (like our `LocalFunctions`) and no `Functions`. 

Following that, I propose to keep the name `LocalFunction` and adjust the other ones as this maybe fits best to the spirit of dune-functions and dune-localfunctions.

1.   `ShapeFunctions` (or `LocalBasisFunctions`)
2.   `LocalFunctions` divided in `ElementFunctions` and `IntersectionFunctions`  
3.   `GridFunctions` (formerly `LocalizableFunctions`)
4.   `Functions` (formerly `SmoothFunctions` and former formerly `GlobalFunctions`)

**Review by ftalbrecht — COMMENTED** [review]
You might also want to rename `interfaces/local-functions.hh` -> `interfaces/element-functions.hh`.

**Comment by TiKeil** [comment]
Good point.

**Comment by tobiasleibner** [comment]
Closing this in favor of #38. Feel free to reopen if this PR is not obsolete.

**Pull request closed without merging**
