### PR TITLE
allow more combinations and more derivatives

### PR DESCRIPTION
**Pull request by ftalbrecht**
This adds +-* for element functions, in addition to functions and grid functions. It also adds derivatives like divergence() for more classes of functions...

### CODE REVIEW

**Comment by ftalbrecht** [comment]
merge when ready

**Comment by renefritze** [comment]
> merge when ready

I haven't actually installed the Bot yet, if that's what you were going for :wink:

**Comment by ftalbrecht** [comment]
On Fri, 2019-03-15 at 02:50 -0700, René Fritze wrote:
> > merge when ready
> 
> I haven't actually installed the Bot yet, if that's what you were
> going for :wink: 
> 

I was indeed... :)

**Comment by tobiasleibner** [comment]
Changes are in #76 now.

**Pull request closed without merging**
