### PR TITLE
Reduce number of test binaries

### PR DESCRIPTION
**Pull request by renefritze**
Since with the addition of laugrid in the testsetup we're now runing into our time limit, I propose to remove ```dim = 2 ``` from the _generic_ static variations. AFAICT the affected functions have no meaningful special case implementation for that, and IMO the useful test is pseudo-scalar ```dim=1``` and vector like ```dim>1```. 
Opinions, @dune-community/dune-xt-functions-devs ?

### CODE REVIEW

**Comment by ftalbrecht** [comment]
I agree to drop useless dimensions. If possible, I would like to test dimDomain = 1, 2, 3 and for each dimDomain: dimRange = 1, dimDomain. That would cover most cases, I think...

**Comment by renefritze** [comment]
For every test on yaspgrid there's no real difference between ```dimDomain == 2,3``` though due to it being a pure tensor grid, right? For Alu there are different implementations, I agree.

**Comment by ftalbrecht** [comment]
We have places with specializations for different dims in some functions. A stupid example is the [default config of the ConstantFunction](https://github.com/dune-community/dune-xt-functions/blob/master/dune/xt/functions/constant.hh#L181), which has nothing to do with the type of the grid. But perhaps I am not getting your point...

**Comment by renefritze** [comment]
There only two cases there ```==1``` and ```!=1```. 
What I'm referring to is that there's no difference in the grid related types we get from yaspgrid. Also, we should not test the general case (```!=1```) for our functions twice. If there is more than one special case in some function we should test that as local as possible. Ie. not in ```functions.mini``` but like for the ```spe10``` function.
Clearer?

**Comment by renefritze** [comment]
ping @ftalbrecht

**Comment by ftalbrecht** [comment]
Im fine with the changes! As I tried to say I would prefer to have something like
```
dimRange = 1, dimDomain | expand
```
in the `functions.mini`, in case we add other `dimDomain`s, but only if possible. Never the less, go ahead as you please!

**Pull request merged**
