### PR TITLE
new-master

### PR DESCRIPTION
**Pull request by ftalbrecht**
This is the `introduce-...` branch of @TiKeil with my own recent changes above. This is supposed to become the new master, as discussed. Pr #29 is thus now obsolete and everyone working on that should checkout the `origin/new-master` branch and start from there. There are still some things missing (some discussed with @TiKeil offline, some not yet documented), I will try to document them in the next days...

### CODE REVIEW

**Comment by renefritze** [comment]
@TiKeil I've already added the binning update here too. Maybe you want to cherry-pick that into your old PR too though to check if it cancels the timeouts, since the tests here still fail on their own.

**Comment by ftalbrecht** [comment]
Some further thoughts, @TiKeil. Regarding `local_function` of `GridFunction`. We discussed to default implement the `local_function(element)` variant by using the other one, but I think this variant is misleading altogether. It was there for historical reasons, but with the new paradigm the user should create the local function before walking the grid, as in _(this example is wrong, see @renemilk comment below)_
```c++
auto lf = func.local_function(element);
for (auto&& element : elements(grid_view))
  lf->bind(element;
```
and not as in
```c++
for (auto&& element : elements(grid_view))
  auto lf = func.local_function(element);
```
The latter example does not make much sense with the new design (the purpose of which was exactly to not create a new function on each element).
So I propose to only keep the
```c++
virtual std::unique_ptr<LocalFunctionType> local_function() const;
```
variant and remove the other one.
This also simplifies the ctors of all local functions since we do not need to support two variants (the one accepting an element can be dropped everywhere).

**Comment by ftalbrecht** [comment]
Some clean up things which are still left to be done:

* `dune/xt/functions/lambda/smooth-function.hh` -> `dune/xt/functions/lambda/function.hh`
  `SmoothLambdaFunction` -> `LambdaFunction`
* `dune/xt/functions/derived.hh -> `dune/xt/functions/base/derived.hh`
* `dune/xt/functions/reinterpret.hh` -> `dune/xt/functions/base/reinterpret.hh`
  `ReinterpretLocalizableFunction` -> `ReinterpretedGridFunction`
* `dune/xt/functions/sliced.hh` -> `dune/xt/functions/base/sliced.hh`
  `SlicedLocalizableFunction` -> `SlicedGridFunction`
* `dune/xt/functions/transformed.hh` -> `dune/xt/functions/base/transformed.hh`
  `TransformedLocalizableFunction` -> `TransformedGridFunction`
* replace all occurences of `Entity*` and `ent*` by `Element*` and `ele*`
* `dimDomain` -> `domain_dim`, `dimRange` -> `range_dim`, `dimRangeCols` -> `range_dim_cols`
* drop `Imp` from template parameters, as in
```c++
template <class ElementImp, size_t rangeDim = 1, size_t rangeDimCols = 1, class RangeFieldImp = double>
class GridFunctionInterface : public Common::ParametricInterface;
```
should become
```c++
template <class Elemen, size_t dim_range = 1, size_t dim_range_cols = 1, class RangeField = double>
class GridFunctionInterface : public Common::ParametricInterface;
```
* update all header guards to match their respective new path
* remove all deprecated header
* remove all deprecated methods and typedefs
* remove all `*.lib.hh` and the respective sections from `CMakeLists.txt`
* remove `dune/xt/functions/interfaces.hh`
* two lines of whitespace between all classes and namespaces

**Comment by renefritze** [comment]
```
auto lf = func.local_function(element);
for (auto&& element : elements(grid_view))
  lf->bind(element;
```
should be
```
auto lf = func.local_function();
for (auto&& element : elements(grid_view))
  lf->bind(element;
```
though? If not, I don't see why the unbound localfunction needs an element?

**Comment by ftalbrecht** [comment]
>  If not, I don't see why the unbound localfunction needs an element?

You are right, of course!

**Comment by ftalbrecht** [comment]
What I forgot to mention: this branch requires

* dune-xt-common: [dailywork-ftschindler](https://github.com/dune-community/dune-xt-common/pull/97)
* dune-xt-la: master
* dune-xt-grid: [Refactor walker functors](https://github.com/dune-community/dune-xt-grid/pull/28)

**Comment by renefritze** [comment]
Does this _really_ need the refactor walker branch? That should be unrelated, no?

**Comment by TiKeil** [comment]
At least I suggest to keep the "refactor walker branch" up to date with the master branch since there are recent changes in the python tests (coming from python_test branch) that we need for performing python bindings tests for dune-xt-functions.

**Comment by ftalbrecht** [comment]
> Does this really need the refactor walker branch? That should be unrelated, no?

Yes, I think you are correct.

**Comment by ftalbrecht** [comment]
Adding to the long list of todos:

* since `post_bind` is protected in the interface, the method should also be `protected` in all derived classes.

**Comment by TiKeil** [comment]
I cannot find a is_bound_ member in ElementFunctionInterface. Did you forget to commit it? 
Anyways, my next commit in #41 will add it then (if that's ok).

**Comment by ftalbrecht** [comment]
> I cannot find a is_bound_ member in ElementFunctionInterface. Did you forget to commit it?

That one is inherited from the `ElementBoundObject` from dune-xt-grid. If this is used there it is probably by mistake (please do not add it). Could you point me to the file/line where I introduced this?

**Comment by TiKeil** [comment]
> That one is inherited from the ElementBoundObject from dune-xt-grid. If this is used there it is probably by mistake (please do not add it). Could you point me to the file/line where I introduced this?

Ok, I'll be waiting for your update. This is where you introduced it: https://github.com/dune-community/dune-xt-functions/pull/38/commits/97fa9a9c3db5491f91f2931e33ca0d1fc2fdf41a
Or do you want me to change it to !(geometry) again?

**Comment by ftalbrecht** [comment]
Ah, that commit is from a different branch and should not (yet) be here. You can just revert the whole commit, thx.

**Comment by TiKeil** [comment]
From my point of view, PR #41  is now ready to merge. There are only minor changes that are left to do.

**Comment by tobiasleibner** [comment]
Release 18.10 is basically done, all dune-xt-modules are now on version 18.11-dev, so this can be merged soon. Does this depend on https://github.com/dune-community/dune-xt-grid/pull/78?

**Comment by ftalbrecht** [comment]
Actually, I am not sure, but could be. We could wait for https://github.com/dune-community/dune-xt-grid/pull/78 to settle before fixing things twice.
Apart from fixing the bugs I left, I am happy with this to be the new master now.
As a reminder: this has to be force-pushed over the current master.

**Comment by tobiasleibner** [comment]
We propably need more bins on Travis again...

**Pull request merged**
